disabled_rules: # Default Rules에서 비활성화할 규칙
    
    # 라인 뒤에 공백이 없어야 합니다. https://realm.github.io/SwiftLint/trailing_whitespace.html
    - trailing_whitespace
    
    # 강제 캐스팅은 피해야합니다. https://realm.github.io/SwiftLint/force_cast.html
    - force_cast
    
    # 강제 언래핑은 피해야합니다. https://realm.github.io/SwiftLint/force_unwrapping.html
    - force_unwrapping
    
    # 한 줄의 길이를 제한합니다.
    - line_length
    
    # 아무 것도 재정의 하지 않는 함수를 제한합니다. https://realm.github.io/SwiftLint/unneeded_override.html
    - unneeded_override
    
    # 튜플의 요소 수 제한 비활성화
    - large_tuple
    
    # Type 이름의 글자 수를 제한합니다. https://realm.github.io/SwiftLint/type_name.html
    - type_name
    
    # String enum value는 enum case 이름과 같을 경우 생략합니다. https://realm.github.io/SwiftLint/redundant_string_enum_value.html
    - redundant_string_enum_value
    
    # 타입 중첩 제한을 비활성화합니다.
    - nesting

opt_in_rules: # Default Rules에서 활성화할 규칙
    
    # Imports should be sorted
    - sorted_imports

# 변수명의 최소 길이를 1로 제한합니다 (제한이 없는 것처럼 동작) https://realm.github.io/SwiftLint/identifier_name.html
identifier_name:
    min_length: 1

type_body_length:
    warning: 500
    error: 600
